# DESCRIPTION: Dockerfile for surveystream_frontend react app

# Build step #1: build the React front end
FROM node:16-alpine AS build-step
ARG BUILD_ENV

WORKDIR  /
ENV PATH=/node_modules/.bin:$PATH

COPY package.json package-lock.json tailwind.config.js /tsconfig.json ./
RUN npm ci
RUN npx -y update-browserslist-db@latest

# Copying source code later so that we can avoid npm install everytime
COPY src src
COPY public public
COPY .env.${BUILD_ENV} .env.${BUILD_ENV}
RUN npm run build:${BUILD_ENV}

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /build /usr/share/nginx/html
# Copy the nginx config template
COPY ./nginx.ecs.conf.template /etc/nginx/conf.d/default.conf.template
# Install envsubst for variable substitution
RUN apk add --no-cache gettext
# Entrypoint to substitute env vars and start nginx
CMD ["sh", "-c", "envsubst '$ALB_BASE_URL' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]