const data = {
  success: true,
  data: [
    {
      survey_uid: 1,
      survey_id: "AgriFieldnet",
      survey_name: "AgriFieldNet main survey form",
      project_name: "",
      survey_description: "",
      survey_method: "",
      irb_approval: "",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "active",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 2,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R3 Education",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "active",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 3,
      survey_id: "AgriFieldnet",
      survey_name: "Digital Green 2.0",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "active",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 4,
      survey_id: "AgriFieldnet",
      survey_name: "Agrifieldnet Main Survey Form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "active",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 5,
      survey_id: "AgriFieldnet",
      survey_name: "TSDPS",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "draft",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 6,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 1.0 main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 7,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R1 Education main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 8,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R1 Health DC main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 9,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R1 Nutrition main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 10,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R1 Health Ben PLW main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
    {
      survey_uid: 11,
      survey_id: "AgriFieldnet",
      survey_name: "ADP 2.0 R1 Nutrition AWC main survey form",
      project_name: "AgriFieldnet Survey",
      survey_description: "",
      survey_method: "in-person",
      irb_approval: "Pending",
      planned_start_date: "2023-01-01",
      planned_end_date: "2023-06-30",
      state: "past",
      last_updated_at: "2022-12-23",
    },
  ],
};

export default data;
