version: "2"
networks:
  credentials_network:
    driver: bridge
    ipam:
      config:
        - subnet: "169.254.170.0/24"
          gateway: 169.254.170.1
services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints:latest-arm64
    volumes:
      - /var/run:/var/run
      - $HOME/.aws/:/home/.aws/
    environment:
      HOME: "/home"
      AWS_PROFILE: "surveystream_dev"
    networks:
      credentials_network:
        ipv4_address: "169.254.170.2"
  client:
    depends_on:
      - ecs-local-endpoints
    networks:
      credentials_network:
        ipv4_address: "169.254.170.5"
    environment:
      AWS_DEFAULT_REGION: "ap-south-1"
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/role/web-task-role"
