version: '2'
services:
  client:
    image: 678681925278.dkr.ecr.ap-south-1.amazonaws.com/dod-surveystream-web-app:frontend
    cpu_shares: 700
    mem_limit: 2000000000
    ports:
      - "443:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: dod_surveystream_webapp
        awslogs-region: ap-south-1
        awslogs-stream-prefix: dod_surveystream_frontend
    links: 
      - "api:api"