version: '2'
services:
  app:
    image: ${STAGING_ACCOUNT}.dkr.ecr.ap-south-1.amazonaws.com/web-callisto-ecr-repository:frontend
    cpu_shares: 300
    mem_limit: 200m
    ports:
      - "443:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: surveystream_webapp_callisto
        awslogs-region: ap-south-1
        awslogs-stream-prefix: surveystream_frontend
